import type { Metadata } from "next";
import { QuizDataProvider } from '@/app/context/QuizDataContext';
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QuizDataProvider>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </QuizDataProvider>
  );
}
